name: test-suite

on: [push]

env:
  # Deny warnings in CI
  RUSTFLAGS: "-D warnings"
  # The Nightly version used for cargo-udeps, might need updating from time to time.
  PINNED_NIGHTLY: nightly-2022-05-20
jobs:
  compile-with-beta-compiler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y git gcc g++ make cmake pkg-config llvm-dev libclang-dev clang protobuf-compiler
    - name: Use Rust beta
      run: rustup override set 1.65
    - name: Run make
      run: make
