name: test-suite

on:
  push:
    branches:
      - stable
      - staging
      - trying
      - 'pr/*'
  pull_request:
env:
  # Deny warnings in CI
  RUSTFLAGS: "-D warnings"
  # The Nightly version used for cargo-udeps, might need updating from time to time.
  PINNED_NIGHTLY: nightly-2022-05-20
jobs:
  compile-with-beta-compiler:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Use Rust beta
          run: rustup override set 1.65
        - name: Run make
          run: make
